lesson 1.3
kmg37/react-todo pull request #4
Opened 2023-10-14 20:38 UTC by kmg37

refactored todolist.js, added event handlers and useState for form

2023-10-16 11:58 UTC, mattcarlotta requested changes
One minor change is required as mentioned below. Otherwise, everything else is looking good.

2023-10-16 11:58 UTC, mattcarlotta commented on src/TodoList.js
> +        <TodoListItem id={props.id} title={props.title} />
Requires changes:
When iterating over an array of items, React needs a `key` property to distinguish which item in the list belongs to which item in the DOM: https://react.dev/learn/rendering-lists

As mentioned in the link above, not providing a key with throw an error in the console:
> Warning: Each child in a list should have a unique “key” prop.

2023-10-16 11:58 UTC, mattcarlotta commented on src/TodoListItem.js
> +function TodoListItem(props) {
Answering question about props naming:
In this case, `props` can be named anything, but it’s mostly a convention that was established before React moved to hooks. Before hooks, React used classes, where `this.props` was used to distinguish between values that were supplied as arguments to a React class component versus `this.state` stateful values created within a React class component. This convention was continued when React moved to hooks to keep it inline with classes. That said, unlike classes, there’s really nothing in hooks that is preventing you from naming it to something else.

2023-10-17 18:21 UTC, kmg37 commented
@mattcarlotta thanks for the information and reference! I've added the key property, looks good in the console now

2023-10-17 18:54 UTC, mattcarlotta approved these changes
Looks good to me!

2023-10-28 15:45 UTC, merged